
const foodArray = [
    {name: "Pizza", price: 12.99, meal: "Lunch", microwaveable: true},
    {name: "Salad", price: 6.99, meal: "Dinner", microwaveable: false},
    {name: "Burger", price: 8.99, meal: "Lunch", microwaveable: false},
    {name: "Sandwich", price: 4.99, meal: "Breakfast", microwaveable: true},
    {name: "Soup", price: 5.99, meal: "Dinner", microwaveable: true},
    {name: "Pasta", price: 9.99, meal: "Lunch", microwaveable: true},
    {name: "Sushi", price: 14.99, meal: "Dinner", microwaveable: false},
    {name: "Omelet", price: 3.99, meal: "Breakfast", microwaveable: true},
    {name: "Burrito", price: 7.99, meal: "Lunch", microwaveable: true},
    {name: "Cake", price: 4.99, meal: "Dessert", microwaveable: false},
    {name: "Steak", price: 15.99, meal: "Dinner", microwaveable: false},
    {name: "Muffin", price: 2.99, meal: "Breakfast", microwaveable: true},
    {name: "Nachos", price: 6.99, meal: "Snack", microwaveable: true},
    {name: "Smoothie", price: 3.99, meal: "Drink", microwaveable: false},
    {name: "Curry", price: 10.99, meal: "Dinner", microwaveable: true},
    {name: "Waffle", price: 4.99, meal: "Breakfast", microwaveable: true},
    {name: "Wrap", price: 5.99, meal: "Lunch", microwaveable: true},
    {name: "Pie", price: 4.99, meal: "Dessert", microwaveable: false},
    {name: "Salmon", price: 12.99, meal: "Dinner", microwaveable: false},
    {name: "Cereal", price: 2.99, meal: "Breakfast", microwaveable: false},
    {name: "Taco", price: 3.99, meal: "Lunch", microwaveable: true},
    {name: "Ice Cream", price: 3.99, meal: "Dessert", microwaveable: false},
    {name: "Chicken", price: 8.99, meal: "Dinner", microwaveable: true},
    {name: "Bagel", price: 2.99, meal: "Breakfast", microwaveable: true},
    {name: "Quesadilla", price: 6.99, meal: "Lunch", microwaveable: true},
    {name: "Cheesecake", price: 5.99, meal: "Dessert", microwaveable: false},
    {name: "Rice", price: 1.99, meal: "Side", microwaveable: true},
    {name: "Coffee", price: 2.99, meal: "Drink", microwaveable: false},
    {name: "Lasagna", price: 11.99, meal: "Dinner", microwaveable: true},
    {name: "Donut", price: 1.99, meal: "Snack", microwaveable: false},
    {name: "Escargot", price: 12.99, meal: "Appetizer", microwaveable: false},
    {name: "Sushi", price: 15.99, meal: "Main Course", microwaveable: false},
    {name: "Baklava", price: 4.99, meal: "Dessert", microwaveable: true},
    {name: "Pad Thai", price: 9.99, meal: "Main Course", microwaveable: true},
    {name: "Gazpacho", price: 6.99, meal: "Soup", microwaveable: false},
    {name: "Hummus", price: 3.99, meal: "Dip", microwaveable: true},
    {name: "Paella", price: 14.99, meal: "Main Course", microwaveable: true},
    {name: "Tiramisu", price: 5.99, meal: "Dessert", microwaveable: false},
    {name: "Kimchi", price: 2.99, meal: "Side Dish", microwaveable: true},
    {name: "Pho", price: 8.99, meal: "Soup", microwaveable: true},
    {name: "Ceviche", price: 11.99, meal: "Appetizer", microwaveable: false},
    {name: "Gelato", price: 3.99, meal: "Dessert", microwaveable: false},
    {name: "Falafel", price: 7.99, meal: "Main Course", microwaveable: true},
    {name: "Borscht", price: 5.99, meal: "Soup", microwaveable: true},
    {name: "Poutine", price: 6.99, meal: "Side Dish", microwaveable: true},
    {name: "Croissant", price: 2.99, meal: "Breakfast", microwaveable: true},
    {name: "Moussaka", price: 12.99, meal: "Main Course", microwaveable: true},
    {name: "Crème Brûlée", price: 4.99, meal: "Dessert", microwaveable: false},
    {name: "Dumplings", price: 8.99, meal: "Appetizer", microwaveable: true},
    {name: "Ramen", price: 7.99, meal: "Main Course", microwaveable: true},
    {name: "Macarons", price: 3.99, meal: "Dessert", microwaveable: false},
    {name: "Salmon Tartare", price: 13.99, meal: "Appetizer", microwaveable: false},
    {name: "Lasagna", price: 11.99, meal: "Main Course", microwaveable: true},
    {name: "Cheesecake", price: 4.99, meal: "Dessert", microwaveable: true},
    {name: "Bruschetta", price: 5.99, meal: "Appetizer", microwaveable: false},
    {name: "Brownies", price: 2.99, meal: "Dessert", microwaveable: true},
    {name: "Burrito", price: 8.99, meal: "Main Course", microwaveable: true}
  ];
  
  export {foodArray};